<?php
/** ACF section groups in page order; maps retained field keys to readable subfield names. */
defined('ABSPATH') || exit();
return [
    'blog-detail' => [
        [
            'name' => 'section_heading',
            'label' => 'Heading',
            'template' => 'content',
            'fields' => [
                'blog_detail_9c13381244a8' => 'breadcrumb',
                'blog_detail_8c780093d5a1' => 'heading',
            ],
        ],
        [
            'name' => 'section_featured_image',
            'label' => 'Featured Image',
            'template' => 'content',
            'fields' => [
                'blog_detail_image_33017e3b40' => 'image',
            ],
        ],
        [
            'name' => 'section_article_body',
            'label' => 'Article Body',
            'template' => 'blog-detail-article-body',
            'fields' => [
                'blog_detail_3ec80043fb9f' => 'description',
                'blog_detail_15daca854069' => 'heading',
                'blog_detail_4fac5cef0a97' => 'description_2',
                'blog_detail_8c8e30bb3e63' => 'heading_2',
                'blog_detail_16e7a84007ce' => 'description_3',
                'blog_detail_44d1e412731f' => 'description_4',
            ],
        ],
        [
            'name' => 'section_local_rankings',
            'label' => 'Local Rankings',
            'template' => 'image-text',
            'fields' => [
                'blog_detail_2c021570ce1c' => 'heading',
                'blog_detail_image_82ae55901c' => 'image',
                'blog_detail_bcb4f48e1767' => 'description',
            ],
        ],
        [
            'name' => 'section_related_posts',
            'label' => 'Related Posts',
            'template' => 'post-grid',
            'fields' => [
                'blog_detail_1624e4d9861e' => 'heading',
                'blog_detail_image_e66cb91b30' => 'image',
                'blog_detail_4d181476ee16' => 'description',
                'blog_detail_4d181476ee16_url' => 'button_url',
                'blog_detail_image_e850bb0d10' => 'image_2',
                'blog_detail_8c5ed5ef437b' => 'description_2',
                'blog_detail_8c5ed5ef437b_url' => 'button_url_2',
                'blog_detail_image_e6018f7e64' => 'image_3',
                'blog_detail_1fab6576ba8d' => 'description_3',
                'blog_detail_1fab6576ba8d_url' => 'button_url_3',
            ],
        ],
    ],
    'services' => [
        [
            'name' => 'section_banner',
            'label' => 'Banner',
            'template' => 'banner',
            'fields' => [
                'services_image_95cc8a2f1e' => 'image',
            ],
        ],
        [
            'name' => 'section_introduction',
            'label' => 'Introduction',
            'template' => 'content',
            'fields' => [
                'services_1d102d9577a4' => 'heading',
                'services_c540653f6d16' => 'heading_2',
                'services_c0d7b44ec821' => 'description',
            ],
        ],
        [
            'name' => 'section_service_grid',
            'label' => 'Service Grid',
            'template' => 'service-grid',
            'fields' => [
                'services_fb1240267041' => 'heading',
                'services_92fa01adc928' => 'subtitle',
                'services_61a499cbf5ad' => 'description',
                'services_403955cd73a3' => 'button_label',
                'services_403955cd73a3_url' => 'button_url',
                'services_b8a1a172da9c' => 'heading_2',
                'services_798933f3ef4e' => 'subtitle_2',
                'services_1b7af68589dc' => 'description_2',
                'services_350220fa15e8' => 'button_label_2',
                'services_350220fa15e8_url' => 'button_url_2',
                'services_879ad37c29e0' => 'heading_3',
                'services_822294744ef5' => 'subtitle_3',
                'services_00de51947158' => 'description_3',
                'services_cf9924922477' => 'button_label_3',
                'services_cf9924922477_url' => 'button_url_3',
                'services_e0dbcb08a264' => 'heading_4',
                'services_a706330f88c5' => 'subtitle_4',
                'services_ff171c150d31' => 'description_4',
                'services_8c6eed7c6379' => 'button_label_4',
                'services_8c6eed7c6379_url' => 'button_url_4',
            ],
        ],
        [
            'name' => 'section_closing_cta',
            'label' => 'Closing CTA',
            'template' => 'statistics',
            'fields' => [
                'services_94024e830fa2' => 'heading',
                'services_bed98f20a891' => 'text',
                'services_8eb4c91b801a' => 'text_2',
                'services_bd0b0253035b' => 'text_3',
                'services_4b4ceb001243' => 'button_label',
                'services_4b4ceb001243_url' => 'button_url',
            ],
        ],
    ],
    'home' => [
        [
            'name' => 'section_hero',
            'label' => 'Hero',
            'template' => 'hero',
            'fields' => [
                'home_image_4b5fa21323' => 'image',
                'home_1d791eb121c5' => 'heading',
                'home_hero_emblem' => 'image_2',
            ],
        ],
        [
            'name' => 'section_introduction',
            'label' => 'Introduction',
            'template' => 'content',
            'fields' => [
                'home_8c4225c0ac7d' => 'heading',
            ],
        ],
        [
            'name' => 'section_search_strategy',
            'label' => 'Search Strategy',
            'template' => 'image-text',
            'fields' => [
                'home_image_d86e7be569' => 'image',
                'home_2263b6f88209' => 'heading',
                'home_d92c033cd119' => 'description',
                'home_6901adf0ab1d' => 'button_label',
                'home_6901adf0ab1d_url' => 'button_url',
            ],
        ],
        [
            'name' => 'section_services',
            'label' => 'Services',
            'template' => 'service-grid',
            'fields' => [
                'home_473db858b064' => 'heading_5',
                'home_536fe4a39b43' => 'heading',
                'home_a2521eac95bf' => 'description',
                'home_c04f66011766' => 'button_label',
                'home_c04f66011766_url' => 'button_url',
                'home_3416c7bfdc6a' => 'heading_2',
                'home_87d8101d772c' => 'description_2',
                'home_fadcbf34d7f6' => 'button_label_2',
                'home_fadcbf34d7f6_url' => 'button_url_2',
                'home_ef6e013268e4' => 'heading_3',
                'home_87c29f9a637c' => 'description_3',
                'home_01079a482a16' => 'button_label_3',
                'home_01079a482a16_url' => 'button_url_3',
                'home_9e841ae19a6e' => 'heading_4',
                'home_c6db28f931d0' => 'description_4',
                'home_4dbc82586a2a' => 'button_label_4',
                'home_4dbc82586a2a_url' => 'button_url_4',
            ],
        ],
        [
            'name' => 'section_search_trends',
            'label' => 'Search Trends',
            'template' => 'image-text',
            'fields' => [
                'home_685fc698bd13' => 'heading',
                'home_ad1e50936d54' => 'description',
                'home_image_d3f8f036db' => 'image',
            ],
        ],
        [
            'name' => 'section_future_strategy',
            'label' => 'Future Strategy',
            'template' => 'image-text',
            'fields' => [
                'home_image_9c76895b7c' => 'image',
                'home_c03395a13124' => 'heading',
                'home_1260983635dc' => 'description',
                'home_20f80fb1ab2f' => 'heading_2',
                'home_58c8c372efdf' => 'button_label',
                'home_58c8c372efdf_url' => 'button_url',
            ],
        ],
        [
            'name' => 'section_testimonial',
            'label' => 'Testimonial',
            'template' => 'testimonial',
            'fields' => [
                'home_c71150b00266' => 'quote_mark',
                'home_71e8d5ebfb3e' => 'description',
                'home_7393b65da373' => 'attribution',
            ],
        ],
        [
            'name' => 'section_results',
            'label' => 'Results',
            'template' => 'statistics',
            'fields' => [
                'home_6666581aab96' => 'heading',
                'home_840918b075ea' => 'years_statistic',
                'home_d17566645c30' => 'description',
                'home_4973267b1258' => 'years_statistic_2',
                'home_ea2e588e1e39' => 'description_2',
                'home_95726762e92f' => 'statistic',
                'home_6b3533e29b8d' => 'description_3',
                'home_2de7aecb8d76' => 'description_4',
                'home_5697044bab17' => 'link_introduction',
                'home_d4db261ea551' => 'button_label',
                'home_d4db261ea551_url' => 'button_url',
            ],
        ],
        [
            'name' => 'section_closing_cta',
            'label' => 'Closing CTA',
            'template' => 'image-text',
            'fields' => [
                'home_09fe6c6170dc' => 'heading',
                'home_26e26ba9efb2' => 'description',
                'home_b48f00ea5554' => 'button_label',
                'home_b48f00ea5554_url' => 'button_url',
                'home_image_0aad8a4a0f' => 'image',
            ],
        ],
    ],
    'search-engine-marketing' => [
        [
            'name' => 'section_banner',
            'label' => 'Banner',
            'template' => 'banner',
            'fields' => [
                'search_engine_marketing_image_96ff85c5d5' => 'image',
            ],
        ],
        [
            'name' => 'section_introduction',
            'label' => 'Introduction',
            'template' => 'content',
            'fields' => [
                'search_engine_marketing_f6246eab32c5' => 'heading',
                'search_engine_marketing_4daf58fc05bf' => 'subtitle',
                'search_engine_marketing_8f8d05ce486c' => 'description',
            ],
        ],
        [
            'name' => 'section_visibility',
            'label' => 'Visibility',
            'template' => 'image-text',
            'fields' => [
                'search_engine_marketing_image_2e8b60cfe5' => 'image',
                'search_engine_marketing_2a5d5198d572' => 'heading',
                'search_engine_marketing_dbbcc6928a34' => 'description',
            ],
        ],
        [
            'name' => 'section_ppc_services',
            'label' => 'Ppc Services',
            'template' => 'image-text',
            'fields' => [
                'search_engine_marketing_9a1901bd9481' => 'description',
                'search_engine_marketing_image_de24625b12' => 'image',
            ],
        ],
        [
            'name' => 'section_benefits',
            'label' => 'Benefits',
            'template' => 'statistics',
            'fields' => [
                'search_engine_marketing_8f270f2a2afd' => 'heading',
                'search_engine_marketing_8ac1ff91ac2a' => 'description',
                'search_engine_marketing_d7c7e6181717' => 'statistic',
                'search_engine_marketing_57c1652a3574' => 'description_2',
                'search_engine_marketing_87a5e5276ed3' => 'heading_2',
                'search_engine_marketing_f063a20ed3bd' => 'description_3',
                'search_engine_marketing_c552a4ad539c' => 'heading_3',
                'search_engine_marketing_b0fd5c696ade' => 'description_4',
                'search_engine_marketing_f56f157847bf' => 'button_label',
                'search_engine_marketing_f56f157847bf_url' => 'button_url',
            ],
        ],
        [
            'name' => 'section_google_ads',
            'label' => 'Google Ads',
            'template' => 'image-text',
            'fields' => [
                'search_engine_marketing_5da4f91cb7c5' => 'heading',
                'search_engine_marketing_c4ab9d94a0db' => 'description',
                'search_engine_marketing_image_f953878ff0' => 'image',
                'search_engine_marketing_c14dc679be7b' => 'description_2',
            ],
        ],
        [
            'name' => 'section_microsoft_ads',
            'label' => 'Microsoft Ads',
            'template' => 'image-text',
            'fields' => [
                'search_engine_marketing_image_843cfc6b8d' => 'image',
                'search_engine_marketing_9b5edf4fcb86' => 'description',
                'search_engine_marketing_9a4e6a600a10' => 'heading',
                'search_engine_marketing_e7514b17f1f3' => 'description_2',
            ],
        ],
        [
            'name' => 'section_faqs',
            'label' => 'FAQs',
            'template' => 'search-engine-marketing-faqs',
            'fields' => [
                'search_engine_marketing_de2d5ec0ff46' => 'heading',
                'search_engine_marketing_image_ba13013ff2' => 'image',
                'search_engine_marketing_e4c9a55704b0' => 'question',
                'search_engine_marketing_e4c9a55704b0_answer' => 'answer',
                'search_engine_marketing_1a8f0aa708c3' => 'question_2',
                'search_engine_marketing_1a8f0aa708c3_answer' => 'answer_2',
                'search_engine_marketing_bb38e3397bbb' => 'question_3',
                'search_engine_marketing_bb38e3397bbb_answer' => 'answer_3',
                'search_engine_marketing_12d045c16ab7' => 'question_4',
                'search_engine_marketing_12d045c16ab7_answer' => 'answer_4',
                'search_engine_marketing_49292f5e4eed' => 'question_5',
                'search_engine_marketing_49292f5e4eed_answer' => 'answer_5',
                'search_engine_marketing_6e5798b9f4ea' => 'question_6',
                'search_engine_marketing_6e5798b9f4ea_answer' => 'answer_6',
                'search_engine_marketing_faq_question_7' => 'question_7',
                'search_engine_marketing_faq_answer_7' => 'answer_7',
                'search_engine_marketing_faq_question_8' => 'question_8',
                'search_engine_marketing_faq_answer_8' => 'answer_8',
                'search_engine_marketing_faq_question_9' => 'question_9',
                'search_engine_marketing_faq_answer_9' => 'answer_9',
            ],
        ],
        [
            'name' => 'section_closing_cta',
            'label' => 'Closing CTA',
            'template' => 'content',
            'fields' => [
                'search_engine_marketing_b1060e1729d0' => 'heading',
                'search_engine_marketing_ca67c83aae59' => 'description',
                'search_engine_marketing_2263d859bf84' => 'button_label',
                'search_engine_marketing_2263d859bf84_url' => 'button_url',
            ],
        ],
    ],
    'blog' => [
        [
            'name' => 'section_hero',
            'label' => 'Hero',
            'template' => 'hero',
            'fields' => [
                'blog_image_a770b85be1' => 'image',
                'blog_2f0c8cf2c985' => 'heading',
                'blog_37a359563ced' => 'description',
            ],
        ],
    ],
    'case-studies' => [
        [
            'name' => 'section_introduction',
            'label' => 'Introduction',
            'template' => 'content',
            'fields' => [
                'case_studies_089cedf19e41' => 'heading',
                'case_studies_b5430be964d4' => 'description',
                'case_studies_8234b4aaee10' => 'description_2',
                'case_studies_5f8c3c80c990' => 'button_label',
                'case_studies_5f8c3c80c990_url' => 'button_url',
            ],
        ],
    ],
    'about' => [
        [
            'name' => 'section_banner',
            'label' => 'Banner',
            'template' => 'banner',
            'fields' => [
                'about_image_8a6938ebd6' => 'image',
            ],
        ],
        [
            'name' => 'section_introduction',
            'label' => 'Introduction',
            'template' => 'content',
            'fields' => [
                'about_f1bcbe1f32e9' => 'heading',
                'about_5364bb9bbe7f' => 'description',
            ],
        ],
        [
            'name' => 'section_audience_strategy',
            'label' => 'Audience Strategy',
            'template' => 'image-text',
            'fields' => [
                'about_feb01315cca8' => 'description',
                'about_595ae388ed18' => 'heading',
                'about_6fd9927a1ee9' => 'description_2',
                'about_image_fabff0a2d1' => 'image',
            ],
        ],
        [
            'name' => 'section_partnership_heading',
            'label' => 'Partnership Heading',
            'template' => 'content',
            'fields' => [
                'about_3fed862d01f7' => 'heading',
            ],
        ],
        [
            'name' => 'section_partnership',
            'label' => 'Partnership',
            'template' => 'image-text',
            'fields' => [
                'about_image_3f841022dd' => 'image',
                'about_95d816dc41a8' => 'description',
                'about_073b5d613eba' => 'description_2',
            ],
        ],
        [
            'name' => 'section_process',
            'label' => 'Process',
            'template' => 'about-process',
            'fields' => [
                'about_da4d2d3bcd37' => 'heading',
                'about_f46b98a005e8' => 'description',
                'about_b871389519ab' => 'number',
                'about_b4e4254098b9' => 'heading_2',
                'about_b4e4254098b9_url' => 'button_url',
                'about_15ecab530a58' => 'description_2',
                'about_a48b87d433a1' => 'number_2',
                'about_bf25e9e3a036' => 'heading_3',
                'about_ef99a48b3104' => 'description_3',
                'about_0bdb2df6cee4' => 'number_3',
                'about_b5f3d5d9b13b' => 'heading_4',
                'about_38dffd506cc7' => 'description_4',
                'about_dc5e50a805d4' => 'number_4',
                'about_77299c25f780' => 'heading_5',
                'about_a62f88959455' => 'description_5',
                'about_9849908bc21e' => 'button_label',
                'about_9849908bc21e_url' => 'button_url_2',
            ],
        ],
        [
            'name' => 'section_team',
            'label' => 'Team',
            'template' => 'about-team',
            'fields' => [
                'about_5182134bb65f' => 'heading',
                'about_3167a1bf8b73' => 'name',
                'about_64c8a292f1a0' => 'heading_2',
                'about_14d648101a42' => 'description',
                'about_0207ec398514' => 'button_label',
                'about_0207ec398514_url' => 'button_url',
                'about_e90a86ecb353' => 'name_2',
                'about_49f625079f2e' => 'heading_3',
                'about_15160ce464b3' => 'description_2',
                'about_c3554bd72d4e' => 'button_label_2',
                'about_c3554bd72d4e_url' => 'button_url_2',
                'about_7db8407b1d3f' => 'heading_4',
                'about_175746524cd8' => 'description_3',
                'about_5d0d58023776' => 'button_label_3',
                'about_5d0d58023776_url' => 'button_url_3',
            ],
        ],
        [
            'name' => 'section_brand_story',
            'label' => 'Brand Story',
            'template' => 'image-text',
            'fields' => [
                'about_cc11b96d229a' => 'heading',
                'about_e6c42fc4a3fa' => 'description',
            ],
        ],
        [
            'name' => 'section_closing_cta',
            'label' => 'Closing CTA',
            'template' => 'content',
            'fields' => [
                'about_8ccc8c3f77e1' => 'heading',
                'about_d48d9c392e5c' => 'description',
                'about_d48d9c392e5c_url' => 'button_url',
                'about_718abc37e0eb' => 'button_label',
                'about_718abc37e0eb_url' => 'button_url_2',
            ],
        ],
    ],
    'case-study-detail' => [
        [
            'name' => 'section_heading',
            'label' => 'Heading',
            'template' => 'content',
            'fields' => [
                'case_study_detail_dac02921ffd6' => 'breadcrumb',
                'case_study_detail_afcd2640f663' => 'heading',
            ],
        ],
        [
            'name' => 'section_featured_image',
            'label' => 'Featured Image',
            'template' => 'content',
            'fields' => [
                'case_study_detail_image_cf7d13020e' => 'image',
            ],
        ],
        [
            'name' => 'section_results',
            'label' => 'Results',
            'template' => 'case-study-detail-results',
            'fields' => [
                'case_study_detail_7ad346f8413b' => 'description',
                'case_study_detail_edf925d1bf1f' => 'description_2',
                'case_study_detail_269299b792ce' => 'description_3',
                'case_study_detail_9a239a17b643' => 'description_4',
                'case_study_detail_0e4af60dbfa0' => 'description_5',
            ],
        ],
        [
            'name' => 'section_testimonial',
            'label' => 'Testimonial',
            'template' => 'testimonial',
            'fields' => [
                'case_study_detail_7e19b95f2be4' => 'quote_mark',
                'case_study_detail_3f5be18822e8' => 'description',
                'case_study_detail_74dd8a1b256d' => 'attribution',
            ],
        ],
        [
            'name' => 'section_challenge',
            'label' => 'Challenge',
            'template' => 'image-text',
            'fields' => [
                'case_study_detail_e27663e17aca' => 'heading',
                'case_study_detail_image_4d97ed1303' => 'image',
                'case_study_detail_1dcedfb52114' => 'description',
            ],
        ],
        [
            'name' => 'section_follow_up',
            'label' => 'Follow Up',
            'template' => 'content',
            'fields' => [
                'case_study_detail_28224860229f' => 'description',
                'case_study_detail_image_26a15581be' => 'image',
            ],
        ],
    ],
    'shared' => [
        [
            'name' => 'section_footer',
            'label' => 'Footer Content',
            'template' => 'layout/site-footer',
            'fields' => [
                'shared_7b3ca0dbb8c9' => 'call_button_label',
                'ps_booking_url' => 'default_page_button_and_footer_call_url',
                'shared_78f8d1b3d0a8' => 'navigation_heading',
                'shared_63ce494a885e' => 'services_heading',
                'shared_4937e4e54c2c' => 'contact_heading',
                'shared_a8e4f9f45c81' => 'copyright_and_legal_text',
            ],
        ],
    ],
];
